"""initial_migration

Revision ID: ee2cdbe8df55
Revises: 
Create Date: 2026-08-19 16:04:50.610261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2cdbe8df55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('invoice_format_prefix', sa.String(length=10), nullable=False),
    sa.Column('approval_threshold_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('business_terms', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_table('restaurant_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'restaurant_id', name='unique_user_restaurant')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('tax_enabled', sa.Boolean(), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('service_charge_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('operating_hours_open', sa.Time(), nullable=True),
    sa.Column('operating_hours_close', sa.Time(), nullable=True),
    sa.Column('table_naming_format', sa.String(length=50), nullable=False),
    sa.Column('cash_drawer_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('table_number', sa.String(length=10), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'table_number', name='unique_location_table_number')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['restaurant_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Enable RLS
    op.execute("ALTER TABLE restaurants ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE restaurants FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE locations ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE locations FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE restaurant_configurations ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE restaurant_configurations FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE location_configurations ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE location_configurations FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE tables ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE tables FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE restaurant_memberships ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE restaurant_memberships FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE user_roles FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY;")

    # Create policies
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON restaurants
        USING (id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
    """)

    op.execute("""
        CREATE POLICY tenant_isolation_policy ON locations
        USING (restaurant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
    """)

    op.execute("""
        CREATE POLICY tenant_isolation_policy ON restaurant_configurations
        USING (restaurant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
    """)

    op.execute("""
        CREATE POLICY tenant_isolation_policy ON location_configurations
        USING (
            restaurant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
            AND (
                NULLIF(current_setting('app.current_location_id', true), '') IS NULL
                OR location_id = NULLIF(current_setting('app.current_location_id', true), '')::uuid
                OR current_setting('app.current_user_role', true) IN ('GM', 'SUPER_ADMIN')
            )
        );
    """)

    op.execute("""
        CREATE POLICY tenant_isolation_policy ON tables
        USING (
            restaurant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
            AND (
                NULLIF(current_setting('app.current_location_id', true), '') IS NULL
                OR location_id = NULLIF(current_setting('app.current_location_id', true), '')::uuid
                OR current_setting('app.current_user_role', true) IN ('GM', 'SUPER_ADMIN')
            )
        );
    """)

    op.execute("""
        CREATE POLICY tenant_isolation_policy ON restaurant_memberships
        USING (restaurant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
    """)

    op.execute("""
        CREATE POLICY tenant_isolation_policy ON user_roles
        USING (
            EXISTS (
                SELECT 1 FROM restaurant_memberships rm
                WHERE rm.id = membership_id
                AND rm.restaurant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
            )
        );
    """)

    op.execute("""
        CREATE POLICY tenant_isolation_policy ON audit_logs
        USING (
            restaurant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
            AND (
                NULLIF(current_setting('app.current_location_id', true), '') IS NULL
                OR location_id = NULLIF(current_setting('app.current_location_id', true), '')::uuid
                OR current_setting('app.current_user_role', true) IN ('GM', 'SUPER_ADMIN')
            )
        );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop RLS policies
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON restaurants;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON locations;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON restaurant_configurations;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON location_configurations;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON tables;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON restaurant_memberships;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON user_roles;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON audit_logs;")

    # Disable RLS
    op.execute("ALTER TABLE restaurants DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE locations DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE restaurant_configurations DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE location_configurations DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE tables DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE restaurant_memberships DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE user_roles DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('tables')
    op.drop_table('location_configurations')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('restaurant_memberships')
    op.drop_table('restaurant_configurations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
